# Generated by Django 5.0.1 on 2024-02-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDRF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
