# Generated by Django 5.0.1 on 2024-03-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDRF', '0002_getimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
    ]
